version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_DATABASE: studyNodejs
    ports:
      - "3307:3306"
    expose:
      - 3306

  backend:
    build:
      context: ../backend-nodejs
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - URL_REACT=http://localhost
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
      # sua 3000:80 -> 80:80 se khong chay port localhost:3000 nua , ma chi chay localhost
    volumes:
      - ../frontend-react/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p project-node-react-mysql up -d